# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.shoot.frame dummy
scoreboard objectives add aj.obtain.frame dummy