# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.subweapon_sword.root] run return 0
execute on passengers if entity @s[tag=aj.subweapon_sword.data] unless data entity @s {data:{rigHash: 'aed156fe4ae82b7f39338af2bfac76a6672ca0848c4ce785a95d61a0eaba1b82'}} on vehicle run function animated_java:subweapon_sword/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1