# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.left_arm.root] run return 0
execute on passengers if entity @s[tag=aj.left_arm.data] unless data entity @s {data:{rigHash: '34a9c7f83beb917e3532f1a9ad38956858bcea55d1140131d399700bed60d633'}} on vehicle run function animated_java:left_arm/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1