# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.player_arm.root] run return 0
execute on passengers if entity @s[tag=aj.player_arm.data] unless data entity @s {data:{rigHash: 'be3803a267b4bd8323409f7109efcadfb1fca640fbbb4a85cf18b12a11387078'}} on vehicle run function animated_java:player_arm/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1