# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.pistol.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'pistol', 'function_path': 'animated_java:pistol/animations/obtain/next_frame'}
execute if score @s aj.obtain.frame matches 61.. run scoreboard players set @s aj.obtain.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.obtain.frame
execute at @s run function animated_java:pistol/animations/obtain/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.obtain.frame 1