# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.pistol.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'pistol', 'function_path': 'animated_java:pistol/animations/obtain/stop'}
tag @s remove aj.pistol.animation.obtain.playing
scoreboard players set @s aj.obtain.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:pistol/animations/obtain/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only