# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pistol.root] run return 0
execute on passengers if entity @s[tag=aj.pistol.data] unless data entity @s {data:{rigHash: '8c1989ec7cf5ea5ebf470d4f4873eff6a5f493dad4a55bdd29dafe33aba16927'}} on vehicle run function animated_java:pistol/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1